PKGDIR     ?= ../..
L4DIR      ?= $(PKGDIR)/../..

TARGET      = $(PKGNAME)_sha1_ref.a $(PKGNAME)_sha1_ref.p.a
SYSTEMS     = x86 arm amd64
PC_FILENAME = $(PKGNAME)_sha1_ref
SRC_C       = sha1.c glue.c

include $(L4DIR)/mk/lib.mk
