PKGDIR     ?= ../..
L4DIR      ?= $(PKGDIR)/../..

TARGET      = $(PKGNAME)_sha1_oslo.a $(PKGNAME)_sha1_oslo.p.a
SYSTEMS     = x86
PC_FILENAME = $(PKGNAME)_sha1_oslo
SRC_C       = sha.c glue.c

include $(L4DIR)/mk/lib.mk
