PKGDIR  ?= ../..
L4DIR   ?= $(PKGDIR)/../..

TARGET   = libgfxbitmap.a 
SRC_C    = font.c bitmap.c

FONTS    = lat0-12.psf lat0-14.psf lat0-16.psf vgafont.psf
SRC_DATA += $(FONTS)

include $(L4DIR)/mk/lib.mk

