PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..

TARGET           = lib4shmc_ringbuf.a lib4shmc_ringbuf.so
PC_FILENAME      = shmc_ringbuf
SRC_C            = ringbuf.c
REQUIRES_LIBS    = shmc

include $(L4DIR)/mk/lib.mk
