PKGDIR	= .
L4DIR	?= $(PKGDIR)/../../..

TARGET		= raw_iface-client
SRC_CC		= client.cc

REQUIRES_LIBS    = libdl libpthread libc_be_sig l4re_c-util libc_support_misc l4re_c

include $(L4DIR)/mk/prog.mk
