PKGDIR	= ../../..
L4DIR	?= $(PKGDIR)/../..

TARGET		= shm_rust-server
SRC_RS		= server.rs

REQUIRES_LIBS    = libpthread libc_be_sig l4re_c-util libc_support_misc l4re-sys-rust l4-sys-rust libl4re-wrapper l4re_c

include $(L4DIR)/mk/prog.mk
