PKGDIR    = ../..
L4DIR    ?= $(PKGDIR)/../..

CONTRIB_HEADERS = y
INCSRC_DIR      = $(PKGDIR_ABS)/lib/contrib/libbacktrace
TARGET          = backtrace.h \
                  $(PKGDIR_ABS)/lib/contrib/include/filenames.h \
                  $(PKGDIR_ABS)/lib/contrib/include/hashtab.h \
                  $(PKGDIR_ABS)/lib/contrib/include/ansidecl.h \
                  $(PKGDIR_ABS)/lib/build/backtrace-supported.h

include $(L4DIR)/mk/include.mk
