PKGDIR	= ../../..
L4DIR	?= $(PKGDIR)/../..

TARGET		= shm_rust-client
SRC_RS		= client.rs

REQUIRES_LIBS    = libpthread libc_be_sig l4re_c-util libc_support_misc libdataspace-rust libcap_sys-rust libl4re-wrapper l4re_c

include $(L4DIR)/mk/prog.mk
