PKGDIR	?= .
L4DIR	?= $(PKGDIR)/../../..

TARGET 		= libl4re-rust.rlib
PC_FILENAME	= l4re-rust
SRC_RS = lib.rs

REQUIRES_LIBS    = l4re_c libl4re-wrapper l4-sys-rust l4-rust

include $(L4DIR)/mk/lib.mk
