PKGDIR   ?= ../..
L4DIR    ?= $(PKGDIR)/../..

CLIENTIDL = ferret_fpages.idl
SRC_C     = fpages.c

MODE      = l4env_minimal

SYSTEMS   = x86-l4f

TARGET    = libferret_fpages.a

include $(L4DIR)/mk/lib.mk
