PKGDIR           ?= ../..
L4DIR            ?= $(PKGDIR)/../..
PLUGIN           := input-libinput
PLUGIN_STATIC_ONLY := y
SRC_CC           := input_libinput.cc
REQUIRES_LIBS   += input

include $(PKGDIR)/plugins/plugin.mk
