[package]
name = "mix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pc-hal = { path = "../pc-hal" }
verix-lib = { path = "../verix-lib" }
bitfield = "0.14.0"
