PKGDIR        ?= ../../..
L4DIR         ?= $(PKGDIR)/../..

TARGET         = lib4dope_vscreen.a
SRC_C          = vscreen.c util.c
PRIVATE_INCDIR = $(PKGDIR)/include

vpath util.c $(PKGDIR)/lib/vscreen/common

include $(L4DIR)/mk/lib.mk

