PKGDIR  ?= ../..
L4DIR   ?= $(PKGDIR)/../..

SYSTEMS       = x86-l4f
TARGET	      = libl4revfs-fs-fuxfs.a libl4revfs-fs-fuxfs.so
LINK_INCR     = libl4revfs-fs-fuxfs.a
PC_FILENAME   = libl4revfs-fs-fuxfs
SRC_CC        = ux.cc
REQUIRES_LIBS = lxfuxlibc

include $(L4DIR)/mk/lib.mk
