PKGDIR     ?= ../..
L4DIR      ?= $(PKGDIR)/../..

TARGET      = $(PKGNAME)_aes_linux_586.o.a $(PKGNAME)_aes_linux_586.o.p.a
SYSTEMS     = x86
PC_FILENAME = $(PKGNAME)_aes_linux_586
SRC_C       = aes.c
SRC_S       = aes-i586-asm.S

include $(L4DIR)/mk/lib.mk
