PKGDIR ?= ..
L4DIR  ?= $(PKGDIR)/../..

EXTRA_TARGET := \
  basic_window \
  box_layout \
  doc/block \
  doc/item \
  doc/link \
  doc/navbar \
  doc/token \
  doc/verbatim \
  document \
  event \
  factory \
  fade_icon \
  fader \
  focus_mixin \
  fonts \
  grid_layout \
  horizontal_shadow \
  icon \
  layout_item \
  layout \
  loadbar \
  message_observer \
  png_image \
  platform \
  pt_factory \
  pt_icon \
  pt_sky_texture \
  redraw_manager \
  scrollbar \
  scroll_pane \
  sky_texture \
  stack_layout \
  style \
  tick \
  titlebar \
  user_state \
  widget \
  window \
  simple_window_deco


include $(L4DIR)/mk/include.mk
