PKGDIR     ?= ../..
L4DIR      ?= $(PKGDIR)/../..

TARGET      = $(PKGNAME)_pad.a $(PKGNAME)_pad.p.a
SYSTEMS     = x86 arm amd64
PC_FILENAME = $(PKGNAME)_pad
SRC_C       = oaep.c

include $(L4DIR)/mk/lib.mk
