PKGDIR	= ..
L4DIR	?= $(PKGDIR)/../..

TARGET		= trust-client
SRC_RS		= client.rs

REQUIRES_LIBS    = libpthread libc_be_sig l4re_c-util libc_support_misc ipc-rs-sys cap-rs-sys libl4re-wrapper
include $(L4DIR)/mk/prog.mk
