PKGDIR          ?= ../..
L4DIR           ?= $(PKGDIR)/../..

TARGET                   = ferret_sensor_dir

REQUIRES_LIBS= libstdc++

SRC_CC = main.cc sensor.cc sensordir.cc

include $(L4DIR)/mk/prog.mk

