PKGDIR     ?= ../..
L4DIR      ?= $(PKGDIR)/../..

TARGET      = $(PKGNAME)_aes_linux.o.a $(PKGNAME)_aes_linux.o.p.a
SYSTEMS     = x86 arm amd64
PC_FILENAME = $(PKGNAME)_aes_linux
SRC_C       = aes.c

include $(L4DIR)/mk/lib.mk
