PKGDIR ?= ../..
L4DIR  ?= $(PKGDIR)/../..

TARGET = dope_control l4lx_control l4lx_verify_cli_mon merge_mon            \
         idle_switch_mon l4lx_histo_mon l4lx_verify_tamed_mon simple_mon

include $(L4DIR)/mk/subdir.mk
