PKGDIR?= ../..
L4DIR ?= $(PKGDIR)/../..

SYSTEMS = x86-l4f

# the name of your library
TARGET	= libevbuf_c.a

PC_FILENAME = libevbuf_c

# list your .c or .cc files here
SRC_C	=
SRC_CC  = eb.cc

include $(L4DIR)/mk/lib.mk
