L4Re - L4 Runtime Environment: L4Re::Util::Dataspace_svr Class Reference
L4Re::Util::Dataspace_svr Class Reference
Dataspace server class.
Public Member Functions
int map (l4_addr_t offset, l4_addr_t local_addr, unsigned long flags, l4_addr_t min_addr, l4_addr_t max_addr, L4::Ipc::Snd_fpage &memory)
Map a region of the dataspace.
virtual int map_hook (l4_addr_t offs, unsigned long flags, l4_addr_t min, l4_addr_t max)
A hook that is called as the first operation in each map request.
virtual int phys (l4_addr_t offset, l4_addr_t &phys_addr, l4_size_t &phys_size) throw ()
Return physical address for a virtual address.
virtual void take () throw ()
Take a reference to this dataspace.
virtual unsigned long release () throw ()
Release a reference to this dataspace.
virtual long copy (l4_addr_t dst_offs, l4_umword_t src_id, l4_addr_t src_offs, unsigned long size) throw ()
Copy from src dataspace to this destination dataspace.
virtual long clear (unsigned long offs, unsigned long size) const throw ()
Clear a region in the dataspace.
virtual long allocate (l4_addr_t offset, l4_size_t size, unsigned access) throw ()
Allocate a region within a dataspace.
virtual unsigned long page_shift () const throw ()
Define the size of the flexpage to map.
virtual bool is_static () const throw ()
Return whether the dataspace is static.
Detailed Description
Dataspace server class.
The default implementation of the interface provides a continuously mapped dataspace.
Definition at line 40 of file dataspace_svr.
Member Function Documentation
allocate()
virtual long L4Re::Util::Dataspace_svr::allocate (l4_addr_t offset, l4_size_t size, unsigned access) throw () inline virtual
Allocate a region within a dataspace.
Parameters
offset Offset in the dataspace, in bytes.
size Size of the range, in bytes.
access Access mode with which the memory backing the dataspace region should be allocated.
Return values
0 Success
<0 Error
Definition at line 168 of file dataspace_svr.
References L4_ENODEV.
Referenced by is_static().
clear()
virtual long L4Re::Util::Dataspace_svr::clear (unsigned long offs, unsigned long size) const throw () virtual
Clear a region in the dataspace.
Parameters
offs Start of the region
size Size of the region
Return values
0 Success
<0 Error
Referenced by copy(), and is_static().
copy()
virtual long L4Re::Util::Dataspace_svr::copy (l4_addr_t dst_offs, l4_umword_t src_id, l4_addr_t src_offs, unsigned long size) throw () inline virtual
Copy from src dataspace to this destination dataspace.
Parameters
dst_offs Offset into the destination dataspace
src_id Local id of the source dataspace
src_offs Offset into the source dataspace
size Number of bytes to copy
Return values
>=0 Number of bytes copied
<0 An error occured. The error code may depend on the implementation.
Definition at line 139 of file dataspace_svr.
References clear(), and L4_ENODEV.
Referenced by is_static().
is_static()
virtual bool L4Re::Util::Dataspace_svr::is_static () const throw () inline virtual
Return whether the dataspace is static.
Returns
True if dataspace is static
Definition at line 184 of file dataspace_svr.
References allocate(), clear(), copy(), L4::Ipc::Gen_fpage< T >::data(), L4Re::Dataspace::Stats::flags, L4::Ipc::Gen_fpage< T >::id_received(), L4_CAP_FPAGE_W, L4_EACCESS, L4_EINVAL, L4_EOK, L4_EPERM, l4_round_size(), map(), page_shift(), phys(), release(), L4Re::Dataspace::Stats::size, and take().
map()
int L4Re::Util::Dataspace_svr::map (l4_addr_t offset, l4_addr_t local_addr, unsigned long flags, l4_addr_t min_addr, l4_addr_t max_addr, L4::Ipc::Snd_fpage & memory)
Map a region of the dataspace.
Parameters
offset Offset to start within data space
local_addr Local address to map to.
flags Map flags, see L4Re::Dataspace::Map_flags.
min_addr Defines start of receive window.
max_addr Defines end of receive window.
[out] memory Send fpage to map
Return values
0 Success
<0 Error
Referenced by is_static().
map_hook()
virtual int L4Re::Util::Dataspace_svr::map_hook (l4_addr_t offs, unsigned long flags, l4_addr_t min, l4_addr_t max) inline virtual
A hook that is called as the first operation in each map request.
Parameters
offs Offs param to map
flags Flags param to map
min Min param to map
max Max param to map
Return values
<0 Error and the map request will be aborted with that error.
>=0 Success
See also
map
Definition at line 90 of file dataspace_svr.
References phys().
page_shift()
virtual unsigned long L4Re::Util::Dataspace_svr::page_shift () const throw () inline virtual
Define the size of the flexpage to map.
Returns
flexpage size
Definition at line 176 of file dataspace_svr.
References L4_LOG2_PAGESIZE.
Referenced by is_static().
phys()
virtual int L4Re::Util::Dataspace_svr::phys (l4_addr_t offset, l4_addr_t & phys_addr, l4_size_t & phys_size) throw () virtual
Return physical address for a virtual address.
Parameters
offset Offset into the dataspace
[out] phys_addr Physical address
[out] phys_size Size of continious physical region
Return values
0 Success
<0 Error
Referenced by is_static(), and map_hook().
release()
virtual unsigned long L4Re::Util::Dataspace_svr::release () throw () inline virtual
Release a reference to this dataspace.
Returns
Number of references to the dataspace
Default does nothing and returns always zero.
Definition at line 124 of file dataspace_svr.
Referenced by is_static().
take()
virtual void L4Re::Util::Dataspace_svr::take () throw () inline virtual
Take a reference to this dataspace.
Default does nothing.
Definition at line 114 of file dataspace_svr.
Referenced by is_static().
The documentation for this class was generated from the following file:
l4/re/util/dataspace_svr