L4Re - L4 Runtime Environment: L4Re::Cap_alloc Class Reference
L4Re::Cap_alloc Class Reference abstract
L4Re C++ Interface » L4Re Util C++ Interface » L4Re Capability API
Capability allocator interface.
Inherited by L4Re::Cap_alloc_t< ALLOC >.
Public Member Functions
virtual L4::Cap< void > alloc ()=0 throw ()
Allocate a capability.
template<typename T >
L4::Cap< T > alloc () throw ()
Allocate a capability.
virtual void free (L4::Cap< void > cap, l4_cap_idx_t task=L4_INVALID_CAP, unsigned unmap_flags=L4_FP_ALL_SPACES)=0 throw ()
Free a capability.
virtual ~Cap_alloc ()=0
Destructor.
Static Public Member Functions
template<typename CAP_ALLOC >
static L4Re::Cap_alloc * get_cap_alloc (CAP_ALLOC &ca)
Construct an instance of a capability allocator.
Detailed Description
Capability allocator interface.
Definition at line 41 of file cap_alloc.
Member Function Documentation
alloc() [1/2]
virtual L4::Cap<void> L4Re::Cap_alloc::alloc () throw () pure virtual
Allocate a capability.
Returns
Capability of type void
Referenced by alloc(), get_cap_alloc(), L4Re::make_shared_cap(), L4Re::make_shared_del_cap(), L4Re::make_unique_cap(), and L4Re::make_unique_del_cap().
alloc() [2/2]
template<typename T > L4::Cap<T> L4Re::Cap_alloc::alloc () throw () inline
Allocate a capability.
Returns
Capability of type T
Definition at line 64 of file cap_alloc.
References alloc(), L4::cap_cast(), free(), L4_FP_ALL_SPACES, L4_INVALID_CAP, and ~Cap_alloc().
free()
virtual void L4Re::Cap_alloc::free (L4::Cap< void > cap, l4_cap_idx_t task = L4_INVALID_CAP, unsigned unmap_flags = L4_FP_ALL_SPACES) throw () pure virtual
Free a capability.
Parameters
cap Capability to free.
task If set, task to unmap the capability from.
unmap_flags Flags for unmap, see l4_unmap_flags_t.
Referenced by alloc(), and get_cap_alloc().
get_cap_alloc()
template<typename CAP_ALLOC > static L4Re::Cap_alloc* L4Re::Cap_alloc::get_cap_alloc (CAP_ALLOC & ca) inline static
Construct an instance of a capability allocator.
Parameters
ca Capability allocator
Returns
Instance of a capability allocator.
Definition at line 90 of file cap_alloc.
References alloc(), free(), L4_FP_ALL_SPACES, and L4_INVALID_CAP.
The documentation for this class was generated from the following file:
l4/re/cap_alloc