L4Re - L4 Runtime Environment: L4::Irq_eoi Class Reference
L4::Irq_eoi Class Reference
Interface for sending an acknowledge message to an object.
Public Member Functions
l4_msgtag_t unmask (unsigned irqnum, l4_umword_t *label=0, l4_timeout_t to=L4_IPC_NEVER, l4_utcb_t *utcb=l4_utcb()) throw ()
Acknowledge the given interrupt line.
Detailed Description
Interface for sending an acknowledge message to an object.
The object is usually an ICU or an IRQ.
Definition at line 41 of file irq.
Member Function Documentation
unmask()
l4_msgtag_t L4::Irq_eoi::unmask (unsigned irqnum, l4_umword_t * label = 0, l4_timeout_t to = L4_IPC_NEVER, l4_utcb_t * utcb = l4_utcb()) throw () inline
Acknowledge the given interrupt line.
Parameters
irqnum The interrupt line that shall be acknowledged.
[out] label If NULL this is a send-only unmask, if not NULL then this operation enters an open wait and the protected label shall be received here.
to The timeout-pair (send and receive) that shall be used for this operation. The receive timeout is used with a non-NULL label only.
utcb UTCB to be used for this operation, usually the UTCB of the calling thread.
Returns
Syscall return tag.
Note
If label is NULL this function is a send-only operation and there is no return value except for a failed send operation. In this case use l4_ipc_error() to check for errors, do not use l4_error(), because l4_error() will always return an error.
Definition at line 63 of file irq.
Referenced by L4::Icu::mask(), L4::Irq::unmask(), and L4::Irq::wait().
The documentation for this class was generated from the following file:
l4/sys/irq