L4Re - L4 Runtime Environment: L4::Cap_base Class Reference
L4::Cap_base Class Reference
Base class for all kinds of capabilities.
#include <l4/sys/capability>
Public Types
enum No_init_type { No_init }
Special value for uninitialized capability objects.
enum Cap_type { Invalid = L4_INVALID_CAP }
Invalid capability type.
Public Member Functions
l4_cap_idx_t cap () const throw ()
Return capability selector.
bool is_valid () const throw ()
Test whether the capability is a valid capability index (i.e., not L4_INVALID_CAP).
l4_fpage_t fpage (unsigned rights=L4_FPAGE_RWX) const throw ()
Return flex-page for the capability.
l4_umword_t snd_base (unsigned grant=0, l4_cap_idx_t base=L4_INVALID_CAP) const throw ()
Return send base.
bool operator== (Cap_base const &o) const throw ()
Test if two capabilities are equal.
bool operator!= (Cap_base const &o) const throw ()
Test if two capabilities are not equal.
l4_msgtag_t validate (l4_utcb_t *u=l4_utcb()) const throw ()
Check whether a capability is present (refers to an object).
l4_msgtag_t validate (Cap< Task > task, l4_utcb_t *u=l4_utcb()) const throw ()
Check whether a capability is present (refers to an object).
void invalidate () throw ()
Set this capability to invalid (L4_INVALID_CAP).
Protected Member Functions
Cap_base (l4_cap_idx_t c) throw ()
Generate a capability from its C representation.
Cap_base (Cap_type cap) throw ()
Constructor to create an invalid capability.
Cap_base (l4_default_caps_t cap) throw ()
Initialize capability with one of the default capabilities.
Cap_base () throw ()
Create an uninitialized instance.
void move (Cap_base const &src) const
Replace this capability with the contents of src.
void copy (Cap_base const &src) const
Copy a capability.
Protected Attributes
l4_cap_idx_t _c
The C representation of a capability selector.
Detailed Description
Base class for all kinds of capabilities.
Attention
This class is not for direct use, use L4::Cap instead.
This class contains all the things that are independent of the type of the object referred by the capability.
See also
L4::Cap for typed capabilities.
Definition at line 25 of file capability.h.
Member Enumeration Documentation
Cap_type
enum L4::Cap_base::Cap_type
Invalid capability type.
Enumerator
Invalid
Invalid capability selector.
Definition at line 43 of file capability.h.
No_init_type
enum L4::Cap_base::No_init_type
Special value for uninitialized capability objects.
Enumerator
No_init
Special value for constructing uninitialized Cap objects.
Definition at line 32 of file capability.h.
Constructor & Destructor Documentation
Cap_base() [1/2]
L4::Cap_base::Cap_base (l4_cap_idx_t c) throw () inline explicit protected
Generate a capability from its C representation.
Parameters
c The C capability
Definition at line 142 of file capability.h.
Cap_base() [2/2]
L4::Cap_base::Cap_base (l4_default_caps_t cap) throw () inline explicit protected
Initialize capability with one of the default capabilities.
Parameters
cap Capability.
Definition at line 153 of file capability.h.
Member Function Documentation
cap()
l4_cap_idx_t L4::Cap_base::cap () const throw () inline
Return capability selector.
Returns
Capability selector.
Definition at line 52 of file capability.h.
Referenced by L4Re::Util::Cap_alloc_base::alloc(), L4vbus::Vbus::assign_dma_domain(), L4::Icu::bind(), L4::cap_cast(), L4::cap_reinterpret_cast(), L4::Irq_mux::chain(), L4Re::Util::Smart_count_cap< Unmap_flags >::copy(), L4Re::Smart_count_cap< Unmap_flags >::copy(), L4::Factory::create_factory(), L4::Factory::create_gate(), L4::Factory::create_irq(), L4::Factory::create_task(), L4::Factory::create_thread(), L4::Factory::create_vm(), L4Re::Util::Smart_cap_auto< Unmap_flags >::free(), L4::Invalid_capability::Invalid_capability(), L4virtio::Svr::Device_t< Ds_data >::mem_info(), L4::Smart_cap< T, SMART >::operator->(), L4::Cap< L4Re::Video::Goos >::operator->(), L4Re::Util::Event_buffer_consumer_t< PAYLOAD >::process(), L4::Ipc_svr::Server_iface::rcv_cap(), L4::Smart_cap< T, SMART >::Smart_cap(), L4::Icu::unbind(), and L4vbus::Icu::vicu().
copy()
void L4::Cap_base::copy (Cap_base const & src) const inline protected
Copy a capability.
Parameters
src the source capability.
After this operation this capability refers to the same object as src.
Definition at line 185 of file capability.h.
References fpage(), is_valid(), L4_BASE_TASK_CAP, L4_CAP_FPAGE_RWSD, and l4_task_map().
Referenced by L4::Cap< L4Re::Video::Goos >::copy(), and L4::Cap< L4Re::Video::Goos >::operator->().
fpage()
l4_fpage_t L4::Cap_base::fpage (unsigned rights = L4_FPAGE_RWX) const throw () inline
Return flex-page for the capability.
Parameters
rights Rights, defaults to 'rwx'
Returns
flex-page
Definition at line 72 of file capability.h.
References l4_obj_fpage().
Referenced by copy(), and move().
is_valid()
bool L4::Cap_base::is_valid () const throw () inline
Test whether the capability is a valid capability index (i.e., not L4_INVALID_CAP).
Returns
True if capability is not invalid, false if invalid
Examples:
examples/libs/l4re/c++/mem_alloc/ma+rm.cc, and examples/libs/l4re/c++/shared_ds/ds_clnt.cc.
Definition at line 60 of file capability.h.
Referenced by L4Re::Rm::attach(), copy(), L4Re::Smart_count_cap< Unmap_flags >::copy(), L4Re::Util::Smart_cap_auto< Unmap_flags >::free(), L4Re::Util::Smart_cap_auto< Unmap_flags >::invalidate(), L4::Ipc::make_cap_full(), move(), and L4Re::Video::View::valid().
move()
void L4::Cap_base::move (Cap_base const & src) const inline protected
Replace this capability with the contents of src.
Parameters
src the source capability.
After the operation this capability refers to the object formerly referd to by the source capability src, and the source capability no longer refers to an object.
Definition at line 169 of file capability.h.
References fpage(), is_valid(), L4_BASE_TASK_CAP, L4_CAP_FPAGE_RWSD, L4_MAP_ITEM_GRANT, and l4_task_map().
Referenced by L4::Cap< L4Re::Video::Goos >::move(), and L4::Cap< L4Re::Video::Goos >::operator->().
snd_base()
l4_umword_t L4::Cap_base::snd_base (unsigned grant = 0, l4_cap_idx_t base = L4_INVALID_CAP) const throw () inline
Return send base.
Parameters
grant True object should be granted.
base Base capability (first in a bundle of aligned capabilities)
Returns
Map object.
Definition at line 83 of file capability.h.
References L4_INVALID_CAP, and l4_map_obj_control().
validate() [1/2]
l4_msgtag_t L4::Cap_base::validate (l4_utcb_t * u = l4_utcb()) const throw () inline
Check whether a capability is present (refers to an object).
Parameters
u UTCB to be used for this operation, usually the UTCB of the calling thread.
Return values
tag.label() > 0 Capability is present (refers to an object).
tag.label() == 0 No capability present (void object).
A capability is considered present when it refers to an existing kernel object.
Definition at line 87 of file capability.
validate() [2/2]
l4_msgtag_t L4::Cap_base::validate (Cap< Task > task, l4_utcb_t * u = l4_utcb()) const throw () inline
Check whether a capability is present (refers to an object).
Parameters
task Task to check the capability in.
u UTCB to be used for this operation, usually the UTCB of the calling thread.
Return values
tag.label() > 0 Capability is present (refers to an object).
tag.label() == 0 No capability present (void object).
A capability is considered present when it refers to an existing kernel object.
Definition at line 83 of file capability.
Field Documentation
_c
l4_cap_idx_t L4::Cap_base::_c protected
The C representation of a capability selector.
Definition at line 196 of file capability.h.
Referenced by L4::Smart_cap< T, SMART >::operator->(), and L4::Smart_cap< T, SMART >::Smart_cap().
The documentation for this class was generated from the following files:
l4/sys/cxx/capability.h
l4/sys/capability