L4Re - L4 Runtime Environment: Kernel Interface Page
Kernel Interface Page
Base API
Kernel Interface Page.
Modules
Fiasco-UX Virtual devices
Virtual hardware devices, provided by Fiasco-UX.
Memory descriptors (C version)
C Interface for KIP memory descriptors.
Data Structures
struct l4_kernel_info_t
L4 Kernel Interface Page.
class L4::Kip::Mem_desc
Memory descriptors stored in the kernel interface page.
Macros
#define L4_KERNEL_INFO_MAGIC (0x4BE6344CL) /* "L4µK" */
Kernel Info Page identifier ("L4µK").
Typedefs
typedef struct l4_kernel_info_t l4_kernel_info_t
L4 Kernel Interface Page.
typedef struct l4_kernel_info_t l4_kernel_info_t
L4 Kernel Interface Page.
Functions
l4_umword_t l4_kip_version (l4_kernel_info_t *kip) L4_NOTHROW
Get the kernel version.
const char * l4_kip_version_string (l4_kernel_info_t *kip) L4_NOTHROW
Get the kernel version string.
int l4_kernel_info_version_offset (l4_kernel_info_t *kip) L4_NOTHROW
Return offset in bytes of version_strings relative to the KIP base.
l4_cpu_time_t l4_kip_clock (l4_kernel_info_t *kip) L4_NOTHROW
Return clock value from the KIP.
l4_umword_t l4_kip_clock_lw (l4_kernel_info_t *kip) L4_NOTHROW
Return least significant machine word of clock value from the KIP.
Detailed Description
Kernel Interface Page.
C interface for the Kernel Interface Page:
C++ interface for the Kernel Interface Page:
Include File
#include <l4/sys/kip>
Include File
#include <l4/sys/kip.h>
Function Documentation
l4_kernel_info_version_offset()
int l4_kernel_info_version_offset (l4_kernel_info_t * kip) inline
Return offset in bytes of version_strings relative to the KIP base.
Parameters
kip Pointer to the kernel info page (KIP).
Returns
offset of version_strings relative to the KIP base address, in bytes.
Definition at line 134 of file kip.h.
Referenced by l4_kip_version_string().
l4_kip_clock()
l4_cpu_time_t l4_kip_clock (l4_kernel_info_t * kip) inline
Return clock value from the KIP.
Parameters
kip Pointer to the kernel info page (KIP).
Returns
Value of the clock field in the KIP.
Definition at line 138 of file kip.h.
References l4_mb().
Referenced by L4::Poll_timeout_kipclock::set(), and L4::Poll_timeout_kipclock::test().
l4_kip_clock_lw()
l4_umword_t l4_kip_clock_lw (l4_kernel_info_t * kip) inline
Return least significant machine word of clock value from the KIP.
Parameters
kip Pointer to the kernel info page (KIP).
Returns
Lower machine word of clock value from the KIP.
Definition at line 160 of file kip.h.
References l4_mb().
l4_kip_version()
l4_umword_t l4_kip_version (l4_kernel_info_t * kip) inline
Get the kernel version.
Parameters
kip Kernel Info Page.
Returns
Kernel version string. 0 if KIP could not be mapped.
Definition at line 126 of file kip.h.
l4_kip_version_string()
const char * l4_kip_version_string (l4_kernel_info_t * kip) inline
Get the kernel version string.
Parameters
kip Kernel Info Page.
Returns
Kernel version string.
Definition at line 130 of file kip.h.
References l4_kernel_info_version_offset().