L4Re – L4 Runtime Environment: Region map interface
Region map interface
L4Re C Interface
Region map C interface.
Enumerations
enum l4re_rm_flags_values {
L4RE_RM_F_R = L4RE_DS_F_R , L4RE_RM_F_W = L4RE_DS_F_W , L4RE_RM_F_X = L4RE_DS_F_X , L4RE_RM_F_RX = L4RE_DS_F_RX ,
L4RE_RM_F_RW = L4RE_DS_F_RW , L4RE_RM_F_RWX = L4RE_DS_F_RWX , L4RE_RM_F_NO_ALIAS = 0x200 , L4RE_RM_F_PAGER = 0x400 ,
L4RE_RM_F_RESERVED = 0x800 , L4RE_RM_CACHING_SHIFT = 4 , L4RE_RM_F_CACHING = L4RE_DS_F_CACHING_MASK , L4RE_RM_REGION_FLAGS = 0xffff ,
L4RE_RM_F_CACHE_NORMAL = L4RE_DS_F_NORMAL , L4RE_RM_F_CACHE_BUFFERED = L4RE_DS_F_BUFFERABLE , L4RE_RM_F_CACHE_UNCACHED = L4RE_DS_F_UNCACHEABLE , L4RE_RM_F_SEARCH_ADDR = 0x20000 ,
L4RE_RM_F_IN_AREA = 0x40000 , L4RE_RM_F_EAGER_MAP = 0x80000 , L4RE_RM_F_ATTACH_FLAGS = 0xf0000
}
Flags for region operations.
Functions
int l4re_rm_reserve_area (l4_addr_t *start, unsigned long size, l4re_rm_flags_t flags, unsigned char align) L4_NOTHROW
int l4re_rm_free_area (l4_addr_t addr) L4_NOTHROW
int l4re_rm_attach (void **start, unsigned long size, l4re_rm_flags_t flags, l4re_ds_t mem, l4re_rm_offset_t offs, unsigned char align) L4_NOTHROW
int l4re_rm_detach (void *addr) L4_NOTHROW
Detach and unmap in current task.
int l4re_rm_detach_ds (void *addr, l4re_ds_t *ds) L4_NOTHROW
Detach, unmap and return affected dataspace in current task.
int l4re_rm_detach_unmap (l4_addr_t addr, l4_cap_idx_t task) L4_NOTHROW
Detach and unmap in specified task.
int l4re_rm_detach_ds_unmap (void *addr, l4re_ds_t *ds, l4_cap_idx_t task) L4_NOTHROW
Detach and unmap in specified task.
int l4re_rm_find (l4_addr_t *addr, unsigned long *size, l4re_rm_offset_t *offset, l4re_rm_flags_t *flags, l4re_ds_t *m) L4_NOTHROW
void l4re_rm_show_lists (void) L4_NOTHROW
Dump region map internal data structures.
int l4re_rm_reserve_area_srv (l4_cap_idx_t rm, l4_addr_t *start, unsigned long size, l4re_rm_flags_t flags, unsigned char align) L4_NOTHROW
int l4re_rm_free_area_srv (l4_cap_idx_t rm, l4_addr_t addr) L4_NOTHROW
int l4re_rm_attach_srv (l4_cap_idx_t rm, void **start, unsigned long size, l4re_rm_flags_t flags, l4re_ds_t mem, l4re_rm_offset_t offs, unsigned char align) L4_NOTHROW
int l4re_rm_detach_srv (l4_cap_idx_t rm, l4_addr_t addr, l4re_ds_t *ds, l4_cap_idx_t task) L4_NOTHROW
int l4re_rm_find_srv (l4_cap_idx_t rm, l4_addr_t *addr, unsigned long *size, l4re_rm_offset_t *offset, l4re_rm_flags_t *flags, l4re_ds_t *m) L4_NOTHROW
void l4re_rm_show_lists_srv (l4_cap_idx_t rm) L4_NOTHROW
Dump region map internal data structures.
Detailed Description
Region map C interface.
Enumeration Type Documentation
l4re_rm_flags_values
enum l4re_rm_flags_values
Flags for region operations.
Enumerator
L4RE_RM_F_R
Region is read-only.
L4RE_RM_F_NO_ALIAS
The region contains exclusive memory that is not mapped anywhere else.
L4RE_RM_F_PAGER
Region has a pager.
L4RE_RM_F_RESERVED
Region is reserved (blocked)
L4RE_RM_CACHING_SHIFT
Start of region mapper cache bits.
L4RE_RM_F_CACHING
Mask of all region manager cache bits.
L4RE_RM_REGION_FLAGS
Mask of all region flags.
L4RE_RM_F_CACHE_NORMAL
Cache bits for normal cacheable memory.
L4RE_RM_F_CACHE_BUFFERED
Cache bits for buffered (write combining) memory.
L4RE_RM_F_CACHE_UNCACHED
Cache bits for uncached memory.
L4RE_RM_F_SEARCH_ADDR
Search for a suitable address range.
L4RE_RM_F_IN_AREA
Search only in area, or map into area.
L4RE_RM_F_EAGER_MAP
Eagerly map the attached data space in.
L4RE_RM_F_ATTACH_FLAGS
Mask of all attach flags.
Definition at line 40 of file rm.h.
Function Documentation
l4re_rm_attach()
int l4re_rm_attach (void ** start, unsigned long size, l4re_rm_flags_t flags, l4re_ds_t mem, l4re_rm_offset_t offs, unsigned char align) inline
Parameters
[in,out] start Virtual start address where the region manager shall attach the data space. If L4Re::Rm::F::Search_addr is given this value is used as the start address to search for a free virtual memory region and the resulting address is returned here. If L4Re::Rm::F::In_area is given the value is used as a selector for the area (see L4Re::Rm::reserve_area) to attach the data space to.
size Size of the data space to attach (in bytes)
flags The flags control how and with which rights the dataspace is attached to the region. See L4Re::Rm::F::Attach_flags and L4Re::Rm::F::Region_flags. The caller must specify the desired rights of the attached region explicitly. The default set of rights is empty. If the F::Eager_map flag is set this function may also return L4Re::Dataspace::map error codes if the mapping fails.
mem Data space
offs Offset into the data space to use
align Alignment of the virtual region, log2-size, default: a page (L4_PAGESHIFT). This is only meaningful if the L4Re::Rm::F::Search_addr flag is used.
Return values
0 Success
-L4_ENOENT No area could be found (see L4Re::Rm::F::In_area)
-L4_EPERM Operation not allowed.
-L4_EINVAL
-L4_EADDRNOTAVAIL The given address is not available.
<0 IPC errors
Makes the whole or parts of a data space visible in the virtual memory of the corresponding task. The corresponding region in the virtual address space is backed with the contents of the dataspace.
Note
When searching for a free place in the virtual address space, the space between start and the end of the virtual address space is searched.
There is no region object created, instead the region is defined by a virtual address within this range (see L4Re::Rm::find).
Returns
0 on success, <0 on error
See also
L4Re::Rm::attach
This function is using the L4::Env::env()->rm() service.
Examples
examples/libs/l4re/c/ma+rm.c.
Definition at line 267 of file rm.h.
References l4re_rm_attach_srv().
l4re_rm_attach_srv()
int l4re_rm_attach_srv (l4_cap_idx_t rm, void ** start, unsigned long size, l4re_rm_flags_t flags, l4re_ds_t mem, l4re_rm_offset_t offs, unsigned char align)
See also
L4Re::Rm::attach
Referenced by l4re_rm_attach().
l4re_rm_detach()
int l4re_rm_detach (void * addr) inline
Detach and unmap in current task.
Parameters
addr Address of the region to detach.
Returns
0 on success, <0 on error
Also
See also
L4Re::Rm::detach
This function is using the L4::Env::env()->rm() service.
Definition at line 277 of file rm.h.
References l4re_rm_detach_srv().
l4re_rm_detach_ds()
int l4re_rm_detach_ds (void * addr, l4re_ds_t * ds) inline
Detach, unmap and return affected dataspace in current task.
Parameters
addr Address of the region to detach.
Return values
ds Returns dataspace that is affected.
Returns
0 on success, <0 on error
Also
See also
L4Re::Rm::detach
This function is using the L4::Env::env()->rm() service.
Examples
examples/libs/l4re/c/ma+rm.c.
Definition at line 290 of file rm.h.
References l4re_rm_detach_srv().
l4re_rm_detach_ds_unmap()
int l4re_rm_detach_ds_unmap (void * addr, l4re_ds_t * ds, l4_cap_idx_t task) inline
Detach and unmap in specified task.
Parameters
addr Address of the region to detach.
Return values
ds Returns dataspace that is affected.
Parameters
task Task to unmap pages from, specify L4_INVALID_CAP to not unmap
Returns
0 on success, <0 on error
Also
See also
L4Re::Rm::detach
This function is using the L4::Env::env()->rm() service.
Definition at line 297 of file rm.h.
References l4re_rm_detach_srv().
l4re_rm_detach_srv()
int l4re_rm_detach_srv (l4_cap_idx_t rm, l4_addr_t addr, l4re_ds_t * ds, l4_cap_idx_t task)
See also
L4Re::Rm::detach
Referenced by l4re_rm_detach(), l4re_rm_detach_ds(), l4re_rm_detach_ds_unmap(), and l4re_rm_detach_unmap().
l4re_rm_detach_unmap()
int l4re_rm_detach_unmap (l4_addr_t addr, l4_cap_idx_t task) inline
Detach and unmap in specified task.
Parameters
addr Address of the region to detach.
task Task to unmap pages from, specify L4_INVALID_CAP to not unmap
Returns
0 on success, <0 on error
Also
See also
L4Re::Rm::detach
This function is using the L4::Env::env()->rm() service.
Definition at line 284 of file rm.h.
References l4re_rm_detach_srv().
l4re_rm_find()
int l4re_rm_find (l4_addr_t * addr, unsigned long * size, l4re_rm_offset_t * offset, l4re_rm_flags_t * flags, l4re_ds_t * m) inline
Returns
0 on success, <0 on error
See also
L4Re::Rm::find
Definition at line 304 of file rm.h.
References l4re_rm_find_srv().
l4re_rm_find_srv()
int l4re_rm_find_srv (l4_cap_idx_t rm, l4_addr_t * addr, unsigned long * size, l4re_rm_offset_t * offset, l4re_rm_flags_t * flags, l4re_ds_t * m)
See also
L4Re::Rm::find
Referenced by l4re_rm_find().
l4re_rm_free_area()
int l4re_rm_free_area (l4_addr_t addr) inline
Returns
0 on success, <0 on error
See also
L4Re::Rm::free_area
This function is using the L4::Env::env()->rm() service.
Definition at line 261 of file rm.h.
References l4re_rm_free_area_srv().
l4re_rm_free_area_srv()
int l4re_rm_free_area_srv (l4_cap_idx_t rm, l4_addr_t addr)
See also
L4Re::Rm::free_area
Referenced by l4re_rm_free_area().
l4re_rm_reserve_area()
int l4re_rm_reserve_area (l4_addr_t * start, unsigned long size, l4re_rm_flags_t flags, unsigned char align) inline
Returns
0 on success, <0 on error
See also
L4Re::Rm::reserve_area
This function is using the L4::Env::env()->rm() service.
Definition at line 253 of file rm.h.
References l4re_rm_reserve_area_srv().
l4re_rm_reserve_area_srv()
int l4re_rm_reserve_area_srv (l4_cap_idx_t rm, l4_addr_t * start, unsigned long size, l4re_rm_flags_t flags, unsigned char align)
See also
L4Re::Rm::reserve_area
Referenced by l4re_rm_reserve_area().
l4re_rm_show_lists()
void l4re_rm_show_lists (void) inline
Dump region map internal data structures.
This function is using the L4::Env::env()->rm() service.
Definition at line 312 of file rm.h.
References l4re_rm_show_lists_srv().