L4Re - L4 Runtime Environment: CPU related functions
CPU related functions
Utility Functions
Functions
int l4util_cpu_has_cpuid (void)
Check whether the CPU supports the "cpuid" instruction.
unsigned int l4util_cpu_capabilities (void)
Returns the CPU capabilities if the "cpuid" instruction is available.
unsigned int l4util_cpu_capabilities_nocheck (void)
Returns the CPU capabilities.
void l4util_cpu_cpuid (unsigned long mode, unsigned long *eax, unsigned long *ebx, unsigned long *ecx, unsigned long *edx)
Generic CPUID access function.
Detailed Description
Function Documentation
l4util_cpu_capabilities()
unsigned int l4util_cpu_capabilities (void) inline
Returns the CPU capabilities if the "cpuid" instruction is available.
Returns
CPU capabilities if the "cpuid" instruction is available, 0 if the "cpuid" instruction is not supported.
Definition at line 97 of file cpu.h.
References EXTERN_C_END, l4util_cpu_capabilities_nocheck(), and l4util_cpu_has_cpuid().
l4util_cpu_capabilities_nocheck()
unsigned int l4util_cpu_capabilities_nocheck (void) inline
Returns the CPU capabilities.
Returns
CPU capabilities.
Definition at line 86 of file cpu.h.
References l4util_cpu_cpuid().
Referenced by l4util_cpu_capabilities().
l4util_cpu_has_cpuid()
int l4util_cpu_has_cpuid (void) inline
Check whether the CPU supports the "cpuid" instruction.
Returns
1 if it has, 0 if it has not
Definition at line 66 of file cpu.h.
Referenced by l4util_cpu_capabilities().