L4Re - L4 Runtime Environment: L4virtio::Svr::Dev_status Struct Reference
L4virtio::Svr::Dev_status Struct Reference
Type of the device status register.
Public Member Functions
Dev_status (l4_uint32_t v)
Make Status from raw value.
bool running () const
Check if the device is in running state.
Data Fields
unsigned char raw
Raw value of the VIRTIO device status register.
typedef cxx::Bitfield< decltype(raw), 0, 0 > acked_bfm_t
Type to access the acked bits (0 to 0) of raw .
acked_bfm_t::Val acked () const
Get the acked bits (0 to 0) of raw .
acked_bfm_t::Ref acked ()
Get a reference to the acked bits (0 to 0) of raw .
typedef cxx::Bitfield< decltype(raw), 1, 1 > driver_bfm_t
Type to access the driver bits (1 to 1) of raw .
driver_bfm_t::Val driver () const
Get the driver bits (1 to 1) of raw .
driver_bfm_t::Ref driver ()
Get a reference to the driver bits (1 to 1) of raw .
typedef cxx::Bitfield< decltype(raw), 2, 2 > driver_ok_bfm_t
Type to access the driver_ok bits (2 to 2) of raw .
driver_ok_bfm_t::Val driver_ok () const
Get the driver_ok bits (2 to 2) of raw .
driver_ok_bfm_t::Ref driver_ok ()
Get a reference to the driver_ok bits (2 to 2) of raw .
typedef cxx::Bitfield< decltype(raw), 3, 3 > features_ok_bfm_t
Type to access the features_ok bits (3 to 3) of raw .
features_ok_bfm_t::Val features_ok () const
Get the features_ok bits (3 to 3) of raw .
features_ok_bfm_t::Ref features_ok ()
Get a reference to the features_ok bits (3 to 3) of raw .
typedef cxx::Bitfield< decltype(raw), 7, 7 > failed_bfm_t
Type to access the failed bits (7 to 7) of raw .
failed_bfm_t::Val failed () const
Get the failed bits (7 to 7) of raw .
failed_bfm_t::Ref failed ()
Get a reference to the failed bits (7 to 7) of raw .
Detailed Description
Type of the device status register.
Definition at line 44 of file virtio.
Member Typedef Documentation
acked_bfm_t
typedef cxx::Bitfield<decltype(raw), 0 , 0 > L4virtio::Svr::Dev_status::acked_bfm_t
Type to access the acked bits (0 to 0) of raw .
Definition at line 52 of file virtio.
driver_bfm_t
typedef cxx::Bitfield<decltype(raw), 1 , 1 > L4virtio::Svr::Dev_status::driver_bfm_t
Type to access the driver bits (1 to 1) of raw .
Definition at line 52 of file virtio.
driver_ok_bfm_t
typedef cxx::Bitfield<decltype(raw), 2 , 2 > L4virtio::Svr::Dev_status::driver_ok_bfm_t
Type to access the driver_ok bits (2 to 2) of raw .
Definition at line 53 of file virtio.
failed_bfm_t
typedef cxx::Bitfield<decltype(raw), 7 , 7 > L4virtio::Svr::Dev_status::failed_bfm_t
Type to access the failed bits (7 to 7) of raw .
Definition at line 55 of file virtio.
features_ok_bfm_t
typedef cxx::Bitfield<decltype(raw), 3 , 3 > L4virtio::Svr::Dev_status::features_ok_bfm_t
Type to access the features_ok bits (3 to 3) of raw .
Definition at line 54 of file virtio.
Member Function Documentation
acked() [1/2]
acked_bfm_t::Val L4virtio::Svr::Dev_status::acked () const inline
Get the acked bits (0 to 0) of raw .
Definition at line 52 of file virtio.
Referenced by L4virtio::Svr::Device_t< Ds_data >::mem_info().
acked() [2/2]
acked_bfm_t::Ref L4virtio::Svr::Dev_status::acked () inline
Get a reference to the acked bits (0 to 0) of raw .
Definition at line 52 of file virtio.
driver() [1/2]
driver_bfm_t::Ref L4virtio::Svr::Dev_status::driver () inline
Get a reference to the driver bits (1 to 1) of raw .
Definition at line 53 of file virtio.
driver() [2/2]
driver_bfm_t::Val L4virtio::Svr::Dev_status::driver () const inline
Get the driver bits (1 to 1) of raw .
Definition at line 53 of file virtio.
Referenced by L4virtio::Svr::Device_t< Ds_data >::mem_info().
driver_ok() [1/2]
driver_ok_bfm_t::Val L4virtio::Svr::Dev_status::driver_ok () const inline
Get the driver_ok bits (2 to 2) of raw .
Definition at line 54 of file virtio.
driver_ok() [2/2]
driver_ok_bfm_t::Ref L4virtio::Svr::Dev_status::driver_ok () inline
Get a reference to the driver_ok bits (2 to 2) of raw .
Definition at line 54 of file virtio.
failed() [1/2]
failed_bfm_t::Val L4virtio::Svr::Dev_status::failed () const inline
Get the failed bits (7 to 7) of raw .
Definition at line 56 of file virtio.
Referenced by L4virtio::Svr::Device_t< Ds_data >::handle_mem_cmd_write(), L4virtio::Svr::Device_t< Ds_data >::mem_info(), and L4virtio::Svr::Dev_config::set_failed().
failed() [2/2]
failed_bfm_t::Ref L4virtio::Svr::Dev_status::failed () inline
Get a reference to the failed bits (7 to 7) of raw .
Definition at line 56 of file virtio.
features_ok() [1/2]
features_ok_bfm_t::Ref L4virtio::Svr::Dev_status::features_ok () inline
Get a reference to the features_ok bits (3 to 3) of raw .
Definition at line 55 of file virtio.
features_ok() [2/2]
features_ok_bfm_t::Val L4virtio::Svr::Dev_status::features_ok () const inline
Get the features_ok bits (3 to 3) of raw .
Definition at line 55 of file virtio.
running()
bool L4virtio::Svr::Dev_status::running () const inline
Check if the device is in running state.
Returns
true if the device is in running state.
The device is in running state when acked(), driver(), features_ok(), and driver_ok() return true, and failed() returns false.
Definition at line 66 of file virtio.
Referenced by L4virtio::Svr::Device_t< Ds_data >::handle_mem_cmd_write().
The documentation for this struct was generated from the following file:
l4/l4virtio/server/virtio