L4Re – L4 Runtime Environment: L4::Triggerable Struct Reference
L4::Triggerable Struct Reference
Interface that allows an object to be triggered by some source.
Public Member Functions
l4_msgtag_t trigger (l4_utcb_t *utcb=l4_utcb()) noexcept
Trigger.
Public Member Functions inherited from L4::Irq_eoi
l4_msgtag_t unmask (unsigned irqnum, l4_umword_t *label=0, l4_timeout_t to=L4_IPC_NEVER, l4_utcb_t *utcb=l4_utcb()) noexcept
Acknowledge the given interrupt line.
Additional Inherited Members
Protected Types inherited from L4::Kobject_t< Triggerable, Irq_eoi, L4_PROTO_IRQ >
typedef Triggerable Class
The target interface type (inheriting from Kobject_t)
typedef Typeid::Iface< PROTO, Triggerable > __Iface
The interface description for the derived class.
typedef Typeid::Merge_list< Typeid::Iface_list< __Iface >, typename Base::__Iface_list > __Iface_list
The list of all RPC interfaces provided directly or through inheritance.
Protected Member Functions inherited from L4::Kobject_t< Triggerable, Irq_eoi, L4_PROTO_IRQ >
L4::Cap< Class > c () const noexcept
Get the capability to ourselves.
Static Protected Member Functions inherited from L4::Kobject_t< Triggerable, Irq_eoi, L4_PROTO_IRQ >
static void __check_protocols__ () noexcept
Helper to check for protocol conflicts.
Detailed Description
Interface that allows an object to be triggered by some source.
This interface is usually used in conjunction with L4::Icu.
Definition at line 78 of file irq.
Member Function Documentation
trigger()
l4_msgtag_t L4::Triggerable::trigger (l4_utcb_t * utcb = l4_utcb()) inline noexcept
Trigger.
Parameters
utcb UTCB to be used for this operation, usually the UTCB of the calling thread.
Returns
Syscall return tag for a send-only operation, use l4_ipc_error() to check for errors (do not use l4_error()).
Note
This function is a send-only operation, this means there is no return value except for a failed send operation. Use l4_ipc_error() to check for errors, do not use l4_error(), because l4_error() will always return an error.
Examples
examples/libs/l4re/c++/shared_ds/ds_clnt.cc.
Definition at line 93 of file irq.
References L4::Kobject::cap(), and l4_irq_trigger_u().
Referenced by L4::Semaphore::up().
The documentation for this struct was generated from the following file:
l4/sys/irq