L4Re - L4 Runtime Environment: x86/l4f/l4/util/port_io.h File Reference
port_io.h File Reference
port I/O functions
#include <l4/sys/compiler.h>
#include <l4/sys/types.h>
#include <x86/l4/util/port_io.h>
#include <l4/sys/utcb.h>
#include <l4/sys/ipc.h>
Functions
int l4util_ioport_map (l4_cap_idx_t sigma0id, unsigned port_start, unsigned log2size)
Map a range of I/O ports.
Detailed Description
port I/O functions
Date
06/2003
Author
Frank Mehnert fm3@o.nosp@m.s.in.nosp@m.f.tu-.nosp@m.dres.nosp@m.den.d.nosp@m.e
Definition in file port_io.h.
Function Documentation
l4util_ioport_map()
int l4util_ioport_map (l4_cap_idx_t sigma0id, unsigned port_start, unsigned log2size) inline
Map a range of I/O ports.
Parameters
sigma0id I/O port service (sigma0).
port_start (Start) Port to request.
log2size Log2size of range to request.
Returns
IPC result: 0 if the range could be successfully mapped on error: IPC failure, or -L4_ENOENT if nothing mapped
Definition at line 56 of file port_io.h.
References l4_buf_regs_t::bdr, l4_buf_regs_t::br, L4_ENOENT, l4_iofpage(), l4_ipc_call(), l4_ipc_error(), L4_IPC_NEVER, L4_ITEM_MAP, l4_msgtag(), l4_msgtag_items(), L4_PROTO_IO_PAGE_FAULT, l4_utcb(), l4_utcb_br(), l4_utcb_mr(), l4_msg_regs_t::mr, and l4_fpage_t::raw.