PKGDIR?= ../..
L4DIR ?= $(PKGDIR)/../..

SYSTEMS     = x86-l4f arm-l4f
PC_FILENAME = libankh_packet_analyzer
TARGET	    = libpacket_analyzer.a
SRC_C	    = analyze.c
PRIVATE_INCDIR += $(SRC_DIR)

include $(L4DIR)/mk/lib.mk
