PKGDIR    ?= ../../..
L4DIR     ?= $(PKGDIR)/../..

SYSTEMS	   = x86-l4f arm-l4f amd64-l4f
TARGET     = liblog-buffer.a
CLIENTIDL  = buffer.idl
IDL_PKGDIR = $(PKGDIR_OBJ)/examples/logcon

include $(L4DIR)/mk/lib.mk
