PKGDIR ?= ..
L4DIR  ?= $(PKGDIR)/../..

TARGET  = aes_linux aes_linux_586 aes_openssl \
          sha1_linux sha1_ref sha1_oslo sha1_openssl \
          sha1_linux_new base64 modes pad rsaref2

include $(L4DIR)/mk/subdir.mk
