PKGDIR          ?= ../../../..
L4DIR           ?= $(PKGDIR)/../..

TARGET              = ex_ns-server ex_ns-client
SRC_CC_ex_ns-server = server.cc
SRC_CC_ex_ns-client = client.cc
REQUIRES_LIBS       = cxx_libc_io cxx_io

include $(L4DIR)/mk/prog.mk

