PKGDIR         ?= ../../..
L4DIR          ?= $(PKGDIR)/../..

TARGET          = fer_scalar_demo
SRC_C           = main.c
SYSTEMS		= x86-l4f

REQUIRES_LIBS+= ferret-common ferret-producer libstdc++


include $(L4DIR)/mk/prog.mk
