PKGDIR        ?= ..
L4DIR         ?= $(PKGDIR)/../..

TARGET         = libc_be_socket_lwip.a libc_be_socket_lwip.so
PC_FILENAME    = libc_be_socket_lwip
SRC_CC         = socket.cc
REQUIRES_LIBS  = lwip libstdc++

include $(L4DIR)/mk/lib.mk
