PKGDIR  = .
L4DIR   ?= $(PKGDIR)/../..

TARGET          = verix
SRC_RS          = verix/src/main.rs

REQUIRES_LIBS    = libdl l4re_c-util l4re libpthread l4sys libc_be_sig l4re_c-util libc_support_misc libl4re-wrapper l4-sys-rust libio-vbus libio l4re-rust l4-rust l4_derive-rust
include $(L4DIR)/mk/prog.mk

