PKGDIR         ?= ../../..
L4DIR          ?= $(PKGDIR)/../..

SYSTEMS         = x86-l4f
SRC_C           = main.c
TARGET          = fer_simple_mon
REQUIRES_LIBS   = ferret-common ferret-consumer libstdc++

include $(L4DIR)/mk/prog.mk
