/*
 * \brief   Internally used IDL interface of don scheduling module
 * \date    2004-04-28
 * \author  Norman Feske <nf2@inf.tu-dresden.de>
 */

/*
 * Copyright (C) 2002-2004  Norman Feske  <nf2@os.inf.tu-dresden.de>
 * Technische Universitaet Dresden, Operating Systems Research Group
 *
 * This file is part of the DOpE package, which is distributed under
 * the  terms  of the  GNU General Public Licence 2.  Please see the
 * COPYING file for details.
 */

interface donsched {

	/*** WAKEUP OF THE WORKER THREAD ***/
	[in, noopcode, noexceptions] void wakeup(void);

	/*** DONATION OF TIME FROM DONATION THREAD TO WORKER THREAD ***/
	[allow_reply_only, noopcode, noexceptions] void donate(void);
};
