PKGDIR       ?= ../..
L4DIR        ?= $(PKGDIR)/../..
SYSTEMS       = x86-l4f amd64-l4f arm-l4f
IDL           = donsched.idl
IDL_FLAGS     = --message-passing -fno-server-loop -fno-dispatcher

include $(L4DIR)/mk/idl.mk

