PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..
TARGET		= scout

vpath %.png $(SRC_DIR)/../data

SCOUTDIR = $(PKGDIR)

SRC_BIN += \
  genode_logo.png \
  launchpad.png \
  setup.png \
  x-ray_small.png \
  liquid_fb_small.png

include $(SCOUTDIR)/mk/scout.mk
