PKGDIR		?= ../../../..
L4DIR		?= $(PKGDIR)/../../..

SUBDIRS :=
SRC_CC  := ide.cc \
           intel_gma500.cc \
           intel_i915.cc \
           marvell_91xx.cc \

include $(PKGDIR)/server/src/lib_subdir.mk
