PKGDIR    = ../..
L4DIR    ?= $(PKGDIR)/../..

CONTRIB_HEADERS = y
PKGNAME         = libudis86
INCSRC_DIR      = $(SRC_DIR)/../contrib
TARGET          = udis86.h \
                  libudis86/itab.h \
                  libudis86/extern.h \
		  libudis86/types.h

include $(L4DIR)/mk/include.mk
