PKGDIR     ?= ../..
L4DIR      ?= $(PKGDIR)/../..

TARGET      = $(PKGNAME)_aes_openssl.a $(PKGNAME)_aes_openssl.p.a
SYSTEMS     = x86
PC_FILENAME = $(PKGNAME)_aes_openssl
SRC_C       = glue.c
SRC_S       = ax86-elf.S

include $(L4DIR)/mk/lib.mk
