PKGDIR     ?= ../..
L4DIR      ?= $(PKGDIR)/../..

TARGET      = $(PKGNAME)_sha1_linux_new.a $(PKGNAME)_sha1_linux_new.p.a
SYSTEMS     = x86 arm amd64
PC_FILENAME = $(PKGNAME)_sha1_linux_new
SRC_C       = sha1.c sha1_generic.c

include $(L4DIR)/mk/lib.mk
