PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..

TARGET		= con_evdemo
LIBS		= -lcon -lconstream-server
SYSTEMS		= x86-l4f

SRC_C		= evdemo.c
PRIVATE_INCDIR	= $(SRC_DIR)/../include

include $(L4DIR)/mk/prog.mk
