PKGDIR	?= ..
L4DIR	?= $(PKGDIR)/../..

TARGET = serial_client \
         trap+emulate \
         hello \
         large_malloc \
         pthread_hello \
         pthread_mutex \
         superpages \
         eventbuf

include $(L4DIR)/mk/subdir.mk
