PKGDIR          ?= ../..
L4DIR           ?= $(PKGDIR)/../..

TARGET           = morpork
SYSTEMS          = x86-l4f arm-l4f
SRC_CC           = main.cc arping.cc
REQUIRES_LIBS    = ankh libboost-lite libpthread

include $(L4DIR)/mk/prog.mk
