PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..

TARGET		= $(PKGNAME)

# list your .c or .cc files here
SRC_C		= main.c
SRC_CC          =

# list requirements of your program here
REQUIRES_LIBS   =

include $(L4DIR)/mk/prog.mk
