PKGDIR?= ../..
L4DIR ?= $(PKGDIR)/../..

# the name of your library
TARGET = libddekit++.a
PC_FILENAME = libddekit++

# list your .c files here

SRC_CC = \
		 condvar.cc \
		 init.cc \
		 initcall.cc \
		 lock.cc \
		 malloc.cc \
		 memory.cc \
		 panic.cc \
		 pci.cc \
		 pgtab.cc \
		 printf.cc \
		 resources.cc \
		 semaphore.cc  \
		 thread.cc

#CXXFLAGS = -Weffc++

include $(L4DIR)/mk/lib.mk
