PKGDIR          ?= ../..
L4DIR           ?= $(PKGDIR)/../..

NOTARGETSTOINSTALL = 1
TARGET             = libdope_gfx.a
PRIVATE_INCDIR     = $(PKGDIR)/server/include
SRC_C              = bigmouse.c   default_fnt.c lat0_12.c \
                     smallmouse.c mono_fnt.c    title_fnt.c \
                     big_fnt.c

include $(L4DIR)/mk/lib.mk

