PKGDIR	= ..
L4DIR	?= $(PKGDIR)/../..

TARGET		= trust-server
SRC_RS		= server.rs

REQUIRES_LIBS    = libpthread libc_be_sig l4re_c-util libc_support_misc libipc-rust-wrapper ipc-rs-sys
include $(L4DIR)/mk/prog.mk
