PKGDIR     ?= ../..
L4DIR      ?= $(PKGDIR)/../..

TARGET      = $(PKGNAME)_base64.o.a $(PKGNAME)_base64.o.p.a
SYSTEMS     = x86 arm amd64
PC_FILENAME = $(PKGNAME)_base64
SRC_C       = base64.c

include $(L4DIR)/mk/lib.mk
