PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..

SRC_C          := tsc-omap3.c kp-omap3.c

TARGET		= libarm_input.o.a
PC_FILENAME    := libdrivers-input
REQUIRES_LIBS   = l4re_c-util libio

include $(L4DIR)/mk/lib.mk
