PKGDIR          ?= ../..
L4DIR           ?= $(PKGDIR)/../..

TARGET          = serial-drv
SRC_CC          = main.cc
REQUIRES_LIBS   = libc_support_misc libio drivers_uart

include $(L4DIR)/mk/prog.mk
