PKGDIR      ?= ../..
L4DIR       ?= $(PKGDIR)/../..

TARGET      = $(PKGNAME)_sha1_linux.a $(PKGNAME)_sha1_linux.p.a
SYSTEMS     = x86 arm amd64
PC_FILENAME = $(PKGNAME)_sha1_linux
SRC_C       = sha1.c

include $(L4DIR)/mk/lib.mk
