PKGDIR ?= ../..
L4DIR  ?= $(PKGDIR)/../..

TARGET  = libvt100.a
SRC_C   = color.c vt100.c buffer.c init.c cursor.c echo.c termcap.c  \
          rw.c getchar.c tabs.c insert.c keymap.c support.c

include $(L4DIR)/mk/lib.mk
