PKGDIR           ?= ../..
L4DIR            ?= $(PKGDIR)/../..

TARGET           := libmag-plugin.o.a
SRC_CC           := plugin.cc
CPPFLAGS	 := -fPIC
LDFLAGS          += --unique

include $(L4DIR)/mk/lib.mk
