PKGDIR ?= ..
L4DIR  ?= $(PKGDIR)/../..

EXTRA_TARGET := \
  blit \
  canvas \
  clip_guard \
  factory \
  font \
  geometry \
  gfx_colors \
  mem_canvas \
  mem_factory \
  mem_texture \
  texture


include $(L4DIR)/mk/include.mk
