PKGDIR         ?= ../../..
L4DIR          ?= $(PKGDIR)/../..

SYSTEMS         = x86-l4f

SRC_C           = main.c

TARGET          = fer_list_demo

REQUIRED_LIBS += libstdc++ libboost ferret-client ferret-common

include $(L4DIR)/mk/prog.mk
