PKGDIR          ?= ../..
L4DIR           ?= $(PKGDIR)/../..

TARGET          = libl4png_wrap.a libl4png_wrap.so
SRC_C           = l4png_wrap.c 
PC_FILENAME     = libl4png_wrap
REQUIRES_LIBS   = zlib libpng

include $(L4DIR)/mk/lib.mk
