PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..

TARGET		         = ex_fb_spectrum_c ex_fb_spectrum_cc
SRC_CC_ex_fb_spectrum_cc = spectrum.cc
SRC_C_ex_fb_spectrum_c   = spectrum_c.c
REQUIRES_LIBS            = libevent l4re_c-util

include $(L4DIR)/mk/prog.mk
