L4DIR	?= ..

TARGET = bid-spec bid-tut building-howto dev-overview l4env-concept html
TARGET = source

doc: $(TARGET)
html: bid-spec bid-tut building-howto dev-overview

include $(L4DIR)/mk/subdir.mk
