PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..

SRC_CC	       += hpet.cc
TARGET		= libdrivers_hpet.a
PC_FILENAME     = libdrivers_hpet

PRIVATE_INCDIR += $(SRC_DIR)/../include 

include $(L4DIR)/mk/lib.mk
