[package]
name = "two_task_ipc-client"
version = "0.1.0"
authors = ["Sebastian Humenda <shumenda@gmx.de>"]

[lib]
name = "two_task_ipc_client"
path = "client.rs"
crate-type = ["staticlib"]

[dependencies.l4]
path = "../../../../l4rust/l4-rust"
default-features = false
features = []
