PKGDIR	= ../../..
L4DIR	?= $(PKGDIR)/../..

TARGET		= two_task_ipc-client
SRC_RS		= client.rs

REQUIRES_LIBS    = libpthread libc_be_sig l4re_c-util libc_support_misc l4-sys-rust libl4re-wrapper
include $(L4DIR)/mk/prog.mk
