PKGDIR     ?= ../..
L4DIR      ?= $(PKGDIR)/../..

TARGET      = $(PKGNAME)_modes.a $(PKGNAME)_modes.p.a
SYSTEMS     = x86 arm amd64
PC_FILENAME = $(PKGNAME)_modes
SRC_C       = cbc.c

include $(L4DIR)/mk/lib.mk
