PKGDIR  ?= ../..
L4DIR   ?= $(PKGDIR)/../..

TARGET       = libc_be_rtc.a libc_be_rtc.so
LINK_INCR    = libc_be_rtc.a
SRC_CC       = gettime.cc
PC_FILENAME  = rtc_libc_be
REQUIRES_LIBS= rtc

include $(L4DIR)/mk/lib.mk
