PKGDIR	?= ../../../../../..
L4DIR	?= $(PKGDIR)/../..

# Force these include files to appear in a special subfolder of dde/
INSTALL_INC_PREFIX = l4/dde/linux26/linux-headers-mach

include $(L4DIR)/mk/include.mk
