PKGDIR ?= ..
L4DIR  ?= $(PKGDIR)/../..

# create examples demonstrating the use of your package in subdirectories
# and list those subdirs in the TARGET variable.
TARGET =

include $(L4DIR)/mk/subdir.mk
