# This (Make)file contains configuration settings for io

# ACPI requires PCI, and ACPI is mandatory on x86 and amd64
CONFIG_L4IO_ACPI     = $(if $(filter x86 amd64,$(ARCH)),y)
CONFIG_L4IO_PCI      = $(if $(CONFIG_L4IO_ACPI),y,y)

# PCI-ID database for descriptive PCI devices
CONFIG_L4IO_PCIID_DB = y
