PKGDIR?= ../..
L4DIR ?= $(PKGDIR)/../..

# the name of your library
TARGET	= libuu.a

PC_FILENAME = libuu

# list your .c or .cc files here
SRC_C	= uu.c 
SRC_CC  =

REQUIRES_LIBS = zlib

include $(L4DIR)/mk/lib.mk
