PKGDIR	?= ..
L4DIR	?= $(PKGDIR)/../../..

TARGET = bench0-client_cc bench0-server_cc
SRC_CC_bench0-client_cc = client.cc
SRC_CC_bench0-server_cc = server.cc
REQUIRES_LIBS            = cxx_libc_io cxx_io l4re_c l4re_c-util

include $(L4DIR)/mk/prog.mk
