PKGDIR          = ..
L4DIR          ?= $(PKGDIR)/../..

CONTRIB_HEADERS = y
PKGNAME         = lwip
INCSRC_DIR      = $(PKGDIR_ABS)/lib
EXTRA_TARGET    = $(SRC_DIR)/lwip-util.h

include $(L4DIR)/mk/include.mk
