PKGDIR    = ../..
L4DIR    ?= $(PKGDIR)/../..

CONTRIB_HEADERS = y
INCSRC_DIR      = $(PKGDIR_ABS)/lib/contrib
TARGET          = jpeglib.h jmorecfg.h jerror.h \
                  $(PKGDIR_ABS)/lib/build/jconfig.h

include $(L4DIR)/mk/include.mk
